version: "3.8"


services:
  web:
    image: nginx:stable-alpine
    container_name: pbpdf
    ports: 
      - "1657:80"
    volumes:
      - ../dist/:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
